# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblPackages = QtWidgets.QLabel(self.layoutWidget)
        self.lblPackages.setObjectName("lblPackages")
        self.verticalLayout.addWidget(self.lblPackages)
        self.txtedtPackages = QtWidgets.QTextEdit(self.layoutWidget)
        self.txtedtPackages.setObjectName("txtedtPackages")
        self.verticalLayout.addWidget(self.txtedtPackages)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblResult = QtWidgets.QLabel(self.layoutWidget1)
        self.lblResult.setObjectName("lblResult")
        self.verticalLayout_2.addWidget(self.lblResult)
        self.txtedtResult = QtWidgets.QTextEdit(self.layoutWidget1)
        self.txtedtResult.setReadOnly(True)
        self.txtedtResult.setMarkdown("")
        self.txtedtResult.setObjectName("txtedtResult")
        self.verticalLayout_2.addWidget(self.txtedtResult)
        self.horizontalLayout.addWidget(self.splitter_2)
        self.grpbxButtons = QtWidgets.QGroupBox(self.centralwidget)
        self.grpbxButtons.setMinimumSize(QtCore.QSize(100, 0))
        self.grpbxButtons.setMaximumSize(QtCore.QSize(100, 16777215))
        self.grpbxButtons.setTitle("")
        self.grpbxButtons.setAlignment(QtCore.Qt.AlignCenter)
        self.grpbxButtons.setFlat(True)
        self.grpbxButtons.setObjectName("grpbxButtons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grpbxButtons)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pshbtnAnalize = QtWidgets.QPushButton(self.grpbxButtons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/ico/setup.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pshbtnAnalize.setIcon(icon)
        self.pshbtnAnalize.setObjectName("pshbtnAnalize")
        self.verticalLayout_3.addWidget(self.pshbtnAnalize)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pshbtnCopy = QtWidgets.QPushButton(self.grpbxButtons)
        self.pshbtnCopy.setObjectName("pshbtnCopy")
        self.verticalLayout_3.addWidget(self.pshbtnCopy)
        spacerItem1 = QtWidgets.QSpacerItem(20, 250, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pshbtnOpenFile = QtWidgets.QPushButton(self.grpbxButtons)
        self.pshbtnOpenFile.setObjectName("pshbtnOpenFile")
        self.verticalLayout_3.addWidget(self.pshbtnOpenFile)
        self.pshbtnSaveFile = QtWidgets.QPushButton(self.grpbxButtons)
        self.pshbtnSaveFile.setObjectName("pshbtnSaveFile")
        self.verticalLayout_3.addWidget(self.pshbtnSaveFile)
        spacerItem2 = QtWidgets.QSpacerItem(20, 96, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.pshbtnHelp = QtWidgets.QPushButton(self.grpbxButtons)
        self.pshbtnHelp.setObjectName("pshbtnHelp")
        self.verticalLayout_3.addWidget(self.pshbtnHelp)
        self.horizontalLayout.addWidget(self.grpbxButtons)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOperation = QtWidgets.QMenu(self.menubar)
        self.menuOperation.setObjectName("menuOperation")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/ico/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/ico/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon2)
        self.actionLoad.setObjectName("actionLoad")
        self.actionAnalize = QtWidgets.QAction(MainWindow)
        self.actionAnalize.setIcon(icon)
        self.actionAnalize.setObjectName("actionAnalize")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main/ico/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon3)
        self.actionCopy.setObjectName("actionCopy")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/main/ico/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon4)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuOperation.addAction(self.actionAnalize)
        self.menuOperation.addAction(self.actionCopy)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOperation.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblPackages.setText(_translate("MainWindow", "Packages"))
        self.lblResult.setText(_translate("MainWindow", "Result"))
        self.txtedtResult.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.pshbtnAnalize.setText(_translate("MainWindow", "Analize"))
        self.pshbtnCopy.setText(_translate("MainWindow", "Copy"))
        self.pshbtnOpenFile.setText(_translate("MainWindow", "Open"))
        self.pshbtnSaveFile.setText(_translate("MainWindow", "Save"))
        self.pshbtnHelp.setText(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOperation.setTitle(_translate("MainWindow", "Operation"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionAnalize.setText(_translate("MainWindow", "Analize"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
import main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
